title: Omega Zimba
description: PhD Student in Mathematics
theme: minimal-mistakes-jekyll

header_pages:
  - _pages/home.md
  - _pages/about.md
  - _pages/research.md
  - _pages/publications.md
  - _pages/teaching.md
  - _pages/cv.md
  - _pages/contact.md

